// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv import removed for Docker deployment as env vars are set via docker-compose
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
